export const ALL_CHECKS_REQUEST = "ALL_CHECKS_REQUEST";
export const ALL_CHECKS_SUCCESS = "ALL_CHECKS_SUCCESS";
export const ALL_CHECKS_ERROR = "ALL_CHECKS_ERROR";

export const CHECK_DETAIL_REQUEST = "CHECK_DETAIL_REQUEST";
export const CHECK_DETAIL_SUCCESS = "CHECK_DETAIL_SUCCESS";
export const CHECK_DETAIL_ERROR = "CHECK_DETAIL_ERROR";

export const DELETE_CHECK_REQUEST = "DELETE_CHECK_REQUEST";
export const DELETE_CHECK_SUCCESS = "DELETE_CHECK_SUCCESS";
export const DELETE_CHECK_ERROR = "DELETE_CHECK_ERROR";